"""add user settings

Revision ID: 42939a4a47f3
Revises: a2e9c207766a
Create Date: 2026-02-18 09:58:57.908317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '42939a4a47f3'
down_revision: Union[str, None] = 'a2e9c207766a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_seconds', sa.Integer(), nullable=False),
    sa.Column('short_break_seconds', sa.Integer(), nullable=False),
    sa.Column('long_break_seconds', sa.Integer(), nullable=False),
    sa.Column('long_break_every', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
